version: '3'
services:
    # FRONTEND CONTAINER
    frontend:
        build: 
            context: ./app
            dockerfile: Dockerfile
            args:
            - CLIENTID=<CLIENT_ID>
            - CLIENTSECRET=<CLIENT_SECRET>
            - BACKENDURL=<BACKEND_URL>
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        env_file:
        - .env
        ports: 
            - "<HOST_PORTS>:80"

#CONTAINERS NETWORK
networks:
  default:
    external:
      name: nginx-proxy
